### ISSUE TITLE
Invalid location

### ISSUE THREAD

**Issue by akashnimare** [sideroad/grunt-wpt#15]
It's not taking array in locations and showing invalid location.
> options: {locations: ['SanJose_IE9', 'Wellington' ] }

**Comment by sideroad** [comment]
SanJose_IE9 and Wellington are invalid locations.
Please check https://www.webpagetest.org/getLocations.php to confirm valid locations.

**Comment by akashnimare** [comment]
It's solved. Thanks @sideroad 🚀 .
