### ISSUE TITLE
name":"WPTAPIError","code":301,"message":"Moved Permanently"

### ISSUE THREAD

**Issue by sinampud** [sideroad/grunt-wpt#17]
Hi,

Getting the below when running the grunt command
**name":"WPTAPIError","code":301,"message":"Moved Permanently"**

GruntFile:
module.exports = function(grunt){
  grunt.initConfig({
    wpt: {
      options: {
        locations: ['Dulles_IE9'],
        key: "MYKEY"
      },
      myTest: {
        options: {
          url: [
            'https://google.com/'
            
          ]
        },
        dest: ''
      }
    }
  });
  grunt.loadNpmTasks('grunt-wpt');
  grunt.registerTask('runner', ['wpt']);
}

**Comment by sideroad** [comment]
The issue caused by webpagetest only permitted HTTPS protocol.
I've changed to use https for public API.
Could you checkit?
If you still have the problem, plz open it.

**Comment by sideroad** [comment]
3.1.2 is fixed version
